extends Node

signal update_lang()

enum LANG {
	en_US,
	fr_FR,
	INVALID,
}

var lang: int = LANG.en_US setget set_lang


func _ready():
	lang = AppManager.user_settings["sec-options"]["values"]["lang"]["value"]


func set_lang(_lang: int) -> void:
	if _lang < LANG.en_US or _lang >= LANG.INVALID:
		_lang = LANG.en_US
	lang = _lang
	AppManager.user_settings["sec-options"]["values"]["lang"]["value"] = lang
	AppManager.save_user_settings()
	emit_signal("update_lang")


func get(text_key: String) -> String:
	return translations[lang][text_key] if translations[lang].has(text_key) else text_key

# List of all keys
var translations = {
	LANG.en_US: {
		"menu.quit": "Quit",
		"menu.multiplayer": "Multiplayer",
		"menu.singleplayer": "Singleplayer",
		"menu.settings": "Settings",
		"menu.profile": "Profile",
		"menu.back": "Back",
		"menu.room_list": "Room List",
		"menu.search": "Search",
		"menu.no_room": "No room found",
		"menu.connection_failed": "Connection failed",
		"menu.create_room": "Create Room",
		"menu.create": "CREATE",
		"menu.connect": "Connect",
		"menu.players": "Players",
		"menu.waiting_players": "Waiting for players...",
		"menu.message_input": "Message...",
		"menu.start": "Start",
		"menu.player_count": "Player Count",
		"menu.bot_difficulty": "Bot Difficulty",
		"menu.easy": "EASY",
		"menu.medium": "MEDIUM",
		"menu.hard": "HARD",
		"menu.play": "Play",
		"menu.volume": "Volume",
		"menu.settings.master": "Master",
		"menu.settings.music": "Music",
		"menu.settings.sounds": "Sounds",
		"menu.rules": "Rules",
		"menu.credits": "Credits",
		"menu.language": "Language",
		"menu.save": "Save",
		"menu.badges": "Badges",
		"menu.rules.gameplay": "Game Play",
		"menu.rules.gameplay_description": "Each turn a player chooses one action only. A player may not pass. After the action is chosen other players have an opportunity to doubt or counter that action. If an action is not doubted or countered, the action automatically succeeds. Doubts are resolved first before any action or counteraction is resolved. The game ends when there is only one player left.",
		"menu.rules.counter": "Counter",
		"menu.rules.countered_by": "Countered By",
		"menu.rules.characters": "Characters",
		"none": "Node",
		"character.assassin": "Assassin",
		"character.assassin.description": "Murder someone for the cost of 3 gold.",
		"character.captain": "Captain",
		"character.captain.description": "Steal 2 coins from an opponent.",
		"character.duke": "Duke",
		"character.duke.description": "Take 3 coins from the Treasure.",
		"character.contessa": "Contessa",
		"character.contessa.description": "Counter the Assassin's ability.",
		"character.ambassador": "Ambassador",
		"character.ambassador.description": "Take 2 cards, choose which, if any, to exchange with your face-down cards.",
		"character.inquisitor": "Inquisitor",
		"character.inquisitor.description": "Exchange 1 card to the Court. OR Look at a player's card and choose if they keep it or exchange it to the Court.",
		"menu.credits.class_project": "Class Project",
		"menu.credits.class_project.description": "This game is a result of a class project at the University of Strasbourg FRANCE.\n\nIt has been made by a group of 9 students, on a period of 15 weeks.",
		"action.income": "Income",
		"action.foreign_aid": "Foreign Aid",
		"action.doubt": "Doubt",
		"action.counter": "Counter",
		"action.counter_with": "Counter with",
		"action.pass": "Pass",
		"action.coup": "COUP",
		"action.duke": "Take 3 coins",
		"action.assassin": "Kill someone",
		"action.captain": "Take 2 coins to someone",
		"action.ambassador": "Exchange 2 cards",
		"action.inquisitor_1": "Exchange 1 card",
		"action.inquisitor_2": "Look at one card",
		"action.actions": "Actions",
		"action.bluffs": "Bluffs",
		"card.invalid": "Invalid Card Name",
		"turn": "Turn",
		"coins": "Coins: ",
		"pause": "Pause",
		"continue": "Continue",
		"main_menu": "Main Menu",
		"menu.enter_username": "Enter a Username",
		"menu.login": "Login",
		"menu.register": "Register",
		"menu.username": "Username",
		"menu.password": "Password",
		"menu.password_confirmation": "Password Confirmation",
		"menu.form.create": "Create",
		"menu.it_is_offline_username": "It is your offline username",
		"menu.submit": "Submit",
		"menu.input_empty": "Input field is empty.",
		"menu.username_too_short": "Username is too short.",
		"menu.username_too_long": "Username is too long.",
		"menu.invalid_char": "Invalid character",
		"menu.allowed_char": "Allowed characters",
		"menu.continue_without_login": "Continue without login",
		"menu.error.connection_failed": "Error connecting to server",
		"menu.error.invalid_log": "Invalid info",
		"menu.menu.room_name_empty": "Room Name must be filled",
		"menu.login_empty": "Username must be filled",
		"menu.password_empty": "Password must be filled",
		"menu.confirmation_empty": "Confirmation must be filled",
		"menu.password_confirmation_no_match": "Password and Confirmation does not match",
		"menu.room_settings": "Room Settings",
		"menu.room_name": "Room Name",
		"menu.room_name_too_long": "Room name too long",
		"achievements": "Achievements",
		"achievement.veteran": "Veteran",
		"achievement.champion": "Champion",
		"achievement.gold_for_days": "Gold for days",
		"achievement.execution": "Execution",
		"achievement.nope": "Nope",
		"achievement.mentalist": "Mentalist",
		"achievement.great_liar": "Great liar",
		"achievement.assassin": "Murderer",
		"achievement.captain": "Thief",
		"achievement.duke": "I'm Rich",
		"achievement.contessa": "Not on my watch",
		"achievement.ambassador": "New Me",
		"achievement.inquisitor_swap": "Swap",
		"achievement.inquisitor_look": "I see you",
		"achievement.veteran.desc": "Play %d games",
		"achievement.champion.desc": "Win %d games",
		"achievement.gold_for_days.desc": "Take a total of %d coins",
		"achievement.execution.desc": "Make %d COUP",
		"achievement.nope.desc": "Make %d successful counter",
		"achievement.mentalist.desc": "Doubt successfully %d times",
		"achievement.great_liar.desc": "Lie successfully %d times",
		"achievement.assassin.desc": "Kill %d character with the Assassin",
		"achievement.captain.desc": "Steal %d coins with the Captain",
		"achievement.duke.desc": "Take %d coins with the Duke",
		"achievement.contessa.desc": "Stop %d assassination with the Contessa",
		"achievement.ambassador.desc": "Use %d times the Ambassador's ability",
		"achievement.inquisitor_swap.desc": "Use %d times the Inquisitor's swap ability",
		"achievement.inquisitor_look.desc": "Use %d times the Inquisitor's look ability",
	},
	LANG.fr_FR: {
		"menu.quit": "Quitter",
		"menu.multiplayer": "Multijoueur",
		"menu.singleplayer": "Jeu en Solo",
		"menu.settings": "Réglages",
		"menu.profile": "Profil",
		"menu.back": "Retour",
		"menu.room_list": "Liste des Salons",
		"menu.search": "Rechercher",
		"menu.no_room": "Aucun salon trouvé",
		"menu.connection_failed": "Connexion échouée",
		"menu.create_room": "Créer un salon",
		"menu.create": "CRÉER",
		"menu.connect": "Connecter",
		"menu.players": "Joueurs",
		"menu.waiting_players": "En attente de joueurs...",
		"menu.message_input": "Message...",
		"menu.start": "Start",
		"menu.player_count": "Nbr. Joueurs",
		"menu.bot_difficulty": "Difficulté IA",
		"menu.easy": "FACILE",
		"menu.medium": "MOYENNE",
		"menu.hard": "DIFFICILE",
		"menu.play": "Jouer",
		"menu.volume": "Volume",
		"menu.settings.master": "Général",
		"menu.settings.music": "Musique",
		"menu.settings.sounds": "Effets",
		"menu.rules": "Règles",
		"menu.credits": "Crédits",
		"menu.language": "Langue",
		"menu.save": "Sauvegarder",
		"menu.badges": "Badges",
		"menu.rules.gameplay": "Principe du jeu",
		"menu.rules.gameplay_description": "Chaque tour un joueur choisit une seule action. Il est impossible de passer son tour. Après le choix de l'action, les autres joueurs peuvent douter ou contrer. Si ce n'est pas le cas l'action est réussite. Les doutes sont résolus en premier. La partie se termine lorsqu'il n'y a plus qu'un joueur en vie.",
		"menu.rules.counter": "Counter",
		"menu.rules.countered_by": "Countered By",
		"none": "Aucun",
		"menu.rules.characters": "Personnages",
		"character.assassin": "Assassin",
		"character.assassin.description": "Tuer quelqu'un en payant 3 pièces d'or.",
		"character.captain": "Capitaine",
		"character.captain.description": "Voler 2 pièces à un adversaire.",
		"character.duke": "Duchesse",
		"character.duke.description": "Prendre 3 or au Trésor.",
		"character.contessa": "Contesse",
		"character.contessa.description": "Contrer la capacité de l'Assassin.",
		"character.ambassador": "Ambassadeur",
		"character.ambassador.description": "Piocher 2 cartes à la Cour, puis chosir 2 cartes de sa main qui seront retournées à la Cour.",
		"character.inquisitor": "Inquisiteur",
		"character.inquisitor.description": "Échanger 1 carte à la Cour. OU Regarder la carte d'un adversaire et lui faire échanger avec la Cour ou lui faire garder sa carte.",
		"menu.credits.class_project": "Projet de Cours",
		"menu.credits.class_project.description": "Ce jeu est le résultat d'un projet de cours à l'Université de Strasbourg FRANCE.\n\nIl a été réalisé par un groupe de 9 étudiants, sur une période de 15 semaines.",
		"action.income": "Revenu",
		"action.foreign_aid": "Aide Étrangère",
		"action.doubt": "Douter",
		"action.counter": "Contrer",
		"action.counter_with": "Contrer avec",
		"action.pass": "Passer",
		"action.coup": "COUP",
		"action.duke": "Prendre 3 pièces",
		"action.assassin": "Tuer quelqu'un",
		"action.captain": "Voler 2 pièces à quelqu'un",
		"action.ambassador": "Échanger 2 cartes",
		"action.inquisitor_1": "Échanger 1 carte",
		"action.inquisitor_2": "Regarder une carte",
		"action.actions": "Actions",
		"action.bluffs": "Bluffs",
		"card.invalid": "Carte Invalide",
		"turn": "Tour",
		"coins": "Pièces : ",
		"pause": "Pause",
		"continue": "Continuer",
		"main_menu": "Menu Principal",
		"menu.enter_username": "Entrer un Pseudo",
		"menu.login": "Se connecter",
		"menu.register": "S'identifier",
		"menu.username": "Pseudo",
		"menu.password": "Mot de passe",
		"menu.password_confirmation": "Confirmez le mot de passe",
		"menu.form.create": "Créer",
		"menu.it_is_offline_username": "C'est votre pseudo hors ligne",
		"menu.submit": "Envoyer",
		"menu.input_empty": "Le champs est vide.",
		"menu.username_too_short": "Le pseudo est trop court.",
		"menu.username_too_long": "Le pseudo est trop long.",
		"menu.invalid_char": "Caractère invalide",
		"menu.allowed_char": "Caractères autorisés ",
		"menu.continue_without_login": "Continuer sans se connecter",
		"menu.error.connection_failed": "Erreur de communication avec le serveur",
		"menu.error.invalid_log": "Informations invalides",
		"menu.menu.room_name_empty": "Le nom du salon doit être renseigné",
		"menu.login_empty": "Le pseudo doit être renseigné",
		"menu.password_empty": "Le mot de passe doit être renseigné",
		"menu.confirmation_empty": "La confirmation doit être renseigné",
		"menu.password_confirmation_no_match": "Le mot de passe et la confirmation sont différent",
		"menu.room_settings": "Réglages du salon",
		"menu.room_name": "Nom du salon",
		"menu.room_name_too_long": "Le nom du salon est trop long",
		"achievements": "Succès",
		"achievement.veteran": "Vétéran",
		"achievement.champion": "Champion",
		"achievement.gold_for_days": "Montagne d'or",
		"achievement.execution": "Exécution",
		"achievement.nope": "Non.",
		"achievement.mentalist": "Mentaliste",
		"achievement.great_liar": "Menteur",
		"achievement.assassin": "Assassin",
		"achievement.captain": "Voleur",
		"achievement.duke": "Je suis riche",
		"achievement.contessa": "Je vous arrête",
		"achievement.ambassador": "Résolution",
		"achievement.inquisitor_swap": "Échange",
		"achievement.inquisitor_look": "Je te vois",
		"achievement.veteran.desc": "Jouer %d parties",
		"achievement.champion.desc": "Gagner %d parties",
		"achievement.gold_for_days.desc": "Prendre un total de %d pièces",
		"achievement.execution.desc": "Faire %d COUP",
		"achievement.nope.desc": "Contrer avec succès %d fois",
		"achievement.mentalist.desc": "Douter avec succès %d fois",
		"achievement.great_liar.desc": "Mentir avec succès %d fois",
		"achievement.assassin.desc": "Tuer %d personnage avec l'Assassin",
		"achievement.captain.desc": "Voler %d pièces avec le Capitaine",
		"achievement.duke.desc": "Prendre %d pièces avec la Duchesse",
		"achievement.contessa.desc": "Empêcher %d assassinats avec la Contesse",
		"achievement.ambassador.desc": "Utiliser %d fois le pouvoir de l'Ambassador",
		"achievement.inquisitor_swap.desc": "Utiliser %d fois le pouvoir d'échange de l'Inquisitor",
		"achievement.inquisitor_look.desc": "Utiliser %d fois le pouvoir d'espion de l'Inquisitor",
	},
}
